services:
  - type: web
    name: aqi-prediction-mlops
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
